
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://drtobybrown.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Toby Brown"
title: "Toby Brown"
description: "Personal website of Toby Brown, blogging mainly for science. Opinions expressed probably belong to someone else."
keywords: "astrophysics, toby, brown, science, astronomy"
favicon: "/img/telescope-bw.ico"

################
# Header layout #
################

black-favicon: "/img/telescope-w.ico"

background-img: "../img/star-trail.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: 4 # Set False for infinite loop, or set any number for finite loop.
type-speed: 0.000001
start-delay: 1000
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "I'm Toby Brown, an astrophysicist at McMaster University."
  - text: "I explore how galaxies evolve."
  - text: "I also talk about science on the side."

me-img: "/img/twitter-hs.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/drtobybrown.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#222629"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: Fasle
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

# disqus-shortname: "toby"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ads-logo.png"
    date: "Published Papers"
    description: "A list of my papers can be found <a href=\"http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?library&libname=my+pubs&libid=5330cd9ef7\" target=\"_blank\">here</a>"
  - image: "/img/timeline/newspaper.jpg"
    date: "Featured in the Press"
    description: "My research has been covered by IFL Science, Daily Telegraph, Gizmodo, Scientific American and more"
  - image: "/img/timeline/mic.jpg"
    date: "Public Speaking"
    description: "I regularly deliver talks to large audiences, including the March for Science, Cosmic Shambles, FameLab and major industry events"
  - image: "/img/timeline/tape.jpg"
    date: "Radio"
    description: "Amongst others, I have provided commentary for the ABC, SpaceTime, RTR-FM and JOY FM"

# First image of the Timeline

timeline-img: "/img/timeline/tapeitelescope.jpg"

###########
# Contact #
###########

email: "tobiashenrybrown@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: "My research focuses on the role of gas in the complex mash-up of physical processes that drive galaxy evolution. \\
# I also talk about science on the side."
# author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  # - title: "facebook"
  #   url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/drtobybrown"
  # - title: "github"
  #   url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/drtobybrown/"

############
# 404 page #
############

err-404-img: "/img/First-World-Problems.jpg"

##################
# GPG on Keybase #
##################

keybase-username: tobybrown
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  Astrophysics: 'about'
  SciCom: 'latest-post'
  Portfolio: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
